### ISSUE TITLE
.csv drag and drop not functioning properly

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#122]
When I drag and drop a .csv into the adding users tool, I get two unwanted outcomes. 

(Im on my macbook and using chrome)

If I drag the csv and release it outside of the box, it simply downloads another copy of the same spreadsheet to my computer. This is confusing since there is a green + icon displayed when dragging it over the screen making me think I could drop it anywhere. 

If I drag it inside the upload a file box, the green + icon goes away, but when I drop it there, nothing seems to happen. 

I pulled up the console, and it doesn't show anything happening at all when I release the .csv into the upload a file box. 

Also note that I was able to drag and drop once, but since then, the above has been my experience. 

![screen shot 2016-05-17 at 11 12 38 am](https://cloud.githubusercontent.com/assets/2973990/15328109/c9a25118-1c21-11e6-82c4-53e11b8eed1f.png)

**Comment by colinking** [comment]
In #124, I've included a fix for your first problem so that the file upload now accepts files whenever they are dropped on the page. 

I wasn't able to reproduce your second issue though. Does this just occur for you when dragging + dropping? If you click the box to select a file from the filesystem, does that also have the same problem? 

Possibly you could show me on our next call and we can resolve it then.
