### ISSUE TITLE
User level designation on bulk upload malfunctioning

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#134]
I was having issues trying to upload users as staff/admin. First when I attempted to put the string "admin" and "Admin" in the role column of the .csv, the system rejected them as invalid. 

I had the same experience when I attempted to put a "3" in the role column of the .csv. 

I then investigated and assumed that the system actually worked like this when it came to role designation in the user upload .csv:

blank = volunteer
1= Staff
2=Admin

So I attempted to upload new staff users with "1" and they ended up as Volunteers. 

Something fishy is happening there.

**Comment by choquette33** [comment]
Related to #130

**Comment by colinking** [comment]
@choquette33: What does the .csv look like that you are uploading to add the staff user? I just tried by uploading [`example.csv`](https://github.com/peacecorps/BonVoyage/blob/master/tests/user_tests/example.csv) and I found that it set the proper access levels for staff/volunteer/admins. Here's the output that I received:

![image](https://cloud.githubusercontent.com/assets/2907397/15448741/f3b83c42-1f37-11e6-94cf-211ec463e3a8.png)

I'm working now to add support for specifying the access level as a string instead of just the number. I'll update this issue when this feature is merged with master.

**Comment by choquette33** [comment]
Its on my work computer, but I think I put a 1 for staff, thinking blank was volunteer. 
It's possible I just got confused. 
Can you go in and change the new Botswana guys to staff?
On May 21, 2016 9:42 AM, Colin notifications@github.com wrote:@choquette33: What does the .csv look like that you are uploading to add the staff user? I just tried by uploading example.csv and I found that it set the proper access levels for staff/volunteer/admins. Here's the output that I received:

I'm working now to add support for specifying the access level as a string instead of just the number. I'll update this issue when this feature is merged with master.

**Comment by colinking** [comment]
@choquette33 I updated Dikitso Letshwiti to be at the staff level. That was the only non-test account that I saw, was there another user to update? I'm going to create an issue for adding a way for admins to promote/demote other users on the profile page.

**Comment by choquette33** [comment]
I think he's the only one to have set up his account so far. The other two are pending invites. 
With the new feature of promotion/demotion you added, we should be good. 
On May 21, 2016 4:14 PM, Colin notifications@github.com wrote:@choquette33 I updated Dikitso Letshwiti to be at the staff level. That was the only non-test account that I saw, was there another user to update? I'm going to create an issue for adding a way for admins to promote/demote other users on the profile page.
