### ISSUE TITLE
Post Request Issue

### ISSUE THREAD

**Issue by Zedive** [peacecorps/BonVoyage#4]
Cannot get a response from the server after posting from the client side.

**Comment by colinking** [comment]
_Note on Issues/Requests:_
Make sure you put **as much** information as possible. Make sure that anyone from this project would be able to read your issue and immediately understand the context. Think of what is required when you ask questions on Stack Overflow. Preferably you would also include code where you site exactly where your problems are happening. I can understand what you are looking for since I was working with you guys on Friday, but for anyone else in this project, they wouldn't know where to start. 
Think about it this way: the more information you add, the more people that can come in and help you with your problem. 

_Now, moving on to figuring out the problem:_
I took a look at the code, and found that you guys were actually successfully making the POST request, but there were a couple errors on the server side. One tip would be to use console.log statements to see if the POST request is reaching the server. 

Here's the broken code:

```
if((userName.toLowerCase=="ben21045@gmail.com")&&(password=="abc123")){
        console.log("success");
        res.redirect("helloworld");
}
```

1) `userName.toLowerCase`: toLowerCase is a function, so you are comparing the function to a String. You just need the parenthesis to fix this (`userName.toLowerCase()`).

2) `res.redirect("helloworld")`: If the if check fails, you still need to return something that indicates that the post request succeeded. Instead of redirecting, you should have the client side handle the redirection and instead return a value that indicates whether the authentication succeeded or not.

Here's an example of how that would be implemented:

```
router.post('/loginsub',function(req, res) {
    var userName = "ben21045@gmail.com";
    var password = "abc123";
    if((userName.toLowerCase()=="ben21045@gmail.com")&&(password=="abc123")){
        console.log("success");
        resp.success = true;
    } else {
        resp.success = false;
    }
    // Return the resp object
    res.send(resp);
});
```

On the client side do this. Note a couple changes: 

1) Use `"method"` instead of `"type"` to indicate GET/POST/etc.. `"type"` is deprecated in favor of method, though it does work as an alias.

2) Provide `"data"` as a JS object instead of a String. You can indicate the type using `"dataType" = "json".

3) Avoid specifying the entire url, just the location that you want to direct the AJAX request towards. This works, but it is a pain when you switch ports or move to production with an actual url (that also might change). This was my fault for telling you guys to use the localhost url on Friday.

4) Use the arguments for the success function to see the returned data. You don't need to specify them all, but it will try to fill them in the order below. Check the jQuery docs if you're ever unsure about what comes when.

5) Use the error function for debugging. It makes it easier to see what is going on and can help you catch server errors.

Alright here's how it looks:

```
$.ajax({
    method: "POST",
    data: {
        "username": v,
        "password": p
    },
    dataType: "json",
    url: "/loginsub",
    success: function(response_data, status, request) {
        if(response_data.success)
            window.location = '/helloworld';
        else
            console.log("Authentication Failed");
    },
        error: function(request, status, error) {
        console.log(error);
    }
});
```

_Looking forward:_
We will want to use a better user authentication method. You guys don't have to implement this right now, but feel free to start reading up on Passport for Node. [Here's a great tutorial](http://mherman.org/blog/2015/01/31/local-authentication-with-passport-and-express-4/).
