### ISSUE TITLE
Invalid json 400 error is thrown when submitting a new request

### ISSUE THREAD

**Issue by seanbae** [peacecorps/BonVoyage#45]

**Comment by colinking** [comment]
For future reference, bodyparser was having trouble parsing the data (application/json format) we were submitting because jQuery's AJAX didn't handle it correctly unless it was converted to a string first. Since almost all other $.ajax post requests in our app use url-encoded requests, I just converted it to that. ($.ajax properly handles that data objects when this is the data type)
