### ISSUE TITLE
Additional Background Information - Botswana Specific

### ISSUE THREAD

**Issue by choquette33** [peacecorps/BonVoyage#51]
This is their current leave request form: 
![image](https://cloud.githubusercontent.com/assets/2973990/13822707/181fd7be-eb7d-11e5-99b0-d16f3e14d945.png)

This is a description of the current process: 

1)  PCV fills out form and gets Supervisor\* or Counterpart\* to sign
2)  Form is then emailed (or faxed, or sometimes SMSed via photos) to Peace Corps
3)  Programming*\* reviews (Program Manager or Programming and Training Coordinator), interacts with PCV as needed to clarify and gather additional info, until Programming signs
4)  If leave is domestic, then [Peace Corps Programming and Training Coordinator] enters the data into VIDA and informs PCV of approval – confirming # leave days used. 
5)  If leave is international, it must then go to [Peace Corps Country Director] for final approval. Then data entered into VIDA**\* and PCV informed of approval and # days used

*- Supervisor or Counterpart is their immediate supervisor in the community and is NOT a Peace Corps Staff member. 

**Programming - Means the volunteer's immediate Peace Corps Staff supervisor. 

***VIDA is a Peace Corps Database where we track most things about our volunteers.

**Comment by choquette33** [comment]
A note on number of leave days: 

There are lots of nuances to leave day counting. It would be hard for the system to automate it, although an “assumed # days used” could be counted automatically.

Travel day to get to nearest border isn’t counted. And since the form can’t know where PCVs live, it’ll be hard to know how to count this. Some PCVs spend a day traveling to the capital to get to the airport (so that day is a freebie), and first day out of country isn’t counted either (so that day is a freebie). But if you count consistently (e.g. first day out of country is always a freebie, and each subsequent day including return day is counted), it’ll be correct 75% of the time…

**Comment by colinking** [comment]
About VIDA: would you want a way to publish data directly to VIDA? 
I would imagine that any interactions with Peace Corps systems may be tricky, so as an alternative, would having a way to export data to a specific format be useful?

**Comment by colinking** [comment]
Also, in regards to having program managers leave comments with approval, would a way to tag users in a comment be useful? This way, in the case that approval is needed from a program manager, the country director (or otherwise) could tag the PM to get their approval.

**Comment by colinking** [comment]
Also, a few details in the above form that aren't available as structured inputs:
- Destination cities
- Mobile number during travel
- Names of other PC volunteers who are also traveling

Are any of these important enough to be added to the submission form or could they be left to the comments?

**Comment by choquette33** [comment]
@colinking 
-For VIDA- I can ask around to see if there is any specific format that would help. (I doubt it)
-Big yes to the tagging in comments. I think this would be very helpful. 
-It makes sense to me that we would include cities. Hopefully we could do that without adding much complication to the travel warnings since they are effectively country wide warnings anyway.

**Comment by colinking** [comment]
@choquette33 In regards to getting program manager and country director approval:

Would the volunteer know which program manager would be responsible for reviewing their request? If so, we could add a field in the submission form where they select their program manager. This way the program manager gets notified about the request (which they can subsequently approve or deny) before it makes its way to the country director (upon manager approval). The way this works could all be very similar to the "assign" feature on GitHub issues.

As an edge case, could country directors ever be the direct program manager for a volunteer? As in, should a volunteer be able to directly assign a country director to a leave request? If not, we would be able to differentiate the staff by adding a data field that indicated if they were a program manager or country director.

**Comment by choquette33** [comment]
@colinking - Yes, the volunteer would be aware of the program manager assigned to them. So, I like the idea proposed above. I love the idea of mirroring the assignment feature on GitHub.... so to go a little further on that. What do you think about the idea of the staff member being able to reassign the request back to the volunteer if there is insufficient data provided in the request?

**Comment by colinking** [comment]
I agree that re-assignment would be useful. Would it be best if this feature is accessible by volunteers and staff alike, in case the volunteer assigns the wrong staff member, or the staff member changes, etc.?

We also need to add a page to allow the volunteer to retroactively make changes to the leave request. Should admins/staff have access to edit leave requests themselves? Or would that just create confusion, and should be left to the volunteers?

**Comment by choquette33** [comment]
@colinking For your edge case, I say yes that's possible. It's also possible that the CD would delegate their responsibility to another staff member so it's not as simple as the CD always does the approval. 

So I would say that a volunteer should be able to assign ANY staff member for their country. If they accidentally assign the CD and skip the program manager, the CD could just reassign the request to the proper program manager. 

Or if the CD has delegated approval authority to some one else, the program manager (who would know who the new person would be) would just assign it to the new person.

**Comment by colinking** [comment]
Interesting. Would there be a better way to brand the approve/deny buttons as the "final say" so that if the program manager wants to pass it to a country directory (or vice versa) they will know to use the assignment feature/comments instead of just clicking approve or deny?

**Comment by choquette33** [comment]
@colinking To answer your question from two comments up. I think we should allow the staff and volunteers to edit a submitted request. Seems like it would be better to give the people freedom to fix errors.

**Comment by choquette33** [comment]
@colinking - Tough call on the re-branding....I think there are multiple things to try there and don't know the best. What do you think about an alert that pops up that explains that the volunteer will be notified of the approval or denial? My thought is that would be enough to catch the mess ups.

**Comment by colinking** [comment]
@choquette33: How did the meeting last week go with the Botswana team?

**Comment by colinking** [comment]
To wrap up this issue, here are the topics we still want to discuss:
- **Volunteer Assignment**: Currently you can only assign a staff member, but Patrick brought up the use case where a staff member may want to request a volunteer to update information in the request. Should we change the assignment feature to be able to assign any staff member OR the volunteer who submitted the request? We would need to also update the label to something like: "Assign a Peace Corps Member for Review". 
- **Approval System**: As we discussed, there are multiple levels of approval and the hierarchy of who gives the final approval is not always well-defined. For example, a program manager may want to give approval and then pass it off to someone else (such as the country director), who then may officially approve the request. Based on the layout of the approval page, the program manager may accidentally click the "approve" button and then possibly re-assign it to the country director, but this would not be the right way to do it. We want to make sure that the "approve" button is not clicked until it has been approved by all involved staff members. What changes should we make to this page in order to encourage this? The end goal would be to encourage the program manager to either:
  - a) Leave a comment, mentioning that they approve of the request, then re-assign to the country director
  - b) We provide a button & dropdown to mark their approval and then select who to re-assign to on the approval page. Then we find a way to differentiate this button from the "approve" button.
  - c) some other solution
- **Phone Numbers for Travel**: The form above directly asks for a phone number during travel. Should we somehow encourage volunteers, when submitting the request, to make sure they have a phone number where staff can reach them at? 
  - We could provide a dropdown where they can select the best phone number to reach them, from the list of phone numbers from the profile page (though this feels unnecessary, since we already have the country that the phone number is associated with). 
  - Or we could add a line of text that links to their profile page and reminds them to add phone numbers before their travel. 
- **Tracking Leave Days**: Do we want to try and tackle this on the site? Based on Patrick's comment above, this appears to be tricky to do, but at the very least we could add a number of days spent on leave per volunteer, so that volunteers and staff could have a general idea of how many travel days have been used. (Though staff would need to know that this isn't the exact number, given the nuances Patrick mentioned.)
- **Warning Notifications**: This is not related specifically to Botswana, but should we send a warning email to staff if a leave request is nearing the travel date and no approval has been given?

Also: is there anything else from the form that wasn't mentioned above, but that should be added to the site? For example, should any of the bulleted lines of text be added?

I would love to hear any input/feedback you guys can think of @choquette33 @SeanBae @furuyahir.

**Comment by colinking** [comment]
- Volunteer Assignment:
  - Only allow assignment to the volunteer who submitted the request (not any other volunteer)
  - Change wording to "Assign Peace Corps Member"
  - When originally submitting the leave request, the volunteer should not be able to assign themselves
- Approval System
  - 1-click reassignment
  - add button to mark as approved
  - create a new issue to discuss mockups
- Phone number during travel
  - One time phone numbers
  - Add inputs to enter phone numbers on the submission form, similar to how it is done on the profile
    page. Replace the travel contact input.
- Tracking Leave Days
  - Ignore for now -- tricky to get it right
- Warning notifications: 👍

**Comment by colinking** [comment]
I believe that everything that we wanted to address with this issue has been taken care of, or formulated into separate issues, so I am going to go ahead and close this issue.
